### PR TITLE
Remove redundant article storage from database

### PR DESCRIPTION
**Pull request by ryanMarq**
Because articles were being stored in both Azure and in Algolia, I removed the code that was storing them in Azure to reduce unnecessary redundancy.

### CODE REVIEW

**Comment by Metatricity** [comment]
I'll be reviewing this. Please give me a moment. =)

**Comment by Metatricity** [comment]
AFAIK - there was no real merge conflict. It was just an empty line vs no line between one line. confusing....

anyway - guess I'd better merge

**Review by JustAnotherUser19401 — CHANGES_REQUESTED** [review]
[redacted]

**Comment by Abrahamh08** [comment]
At first, I thought this extra redundancy would provide an easier migration route, so I thought it should be kept. However, it's just as easy to query the database and make reads on the contract addresses, so I will approve this change once you make the requested changes.

**Comment by Abrahamh08** [comment]
Wait, no. Everything should still be stored so that we can add more stuff later like reputation that shouldn't be part of indexing.

**Pull request closed without merging**
